### PR TITLE
Fix exception in update_callback for disabled devices

### PR DESCRIPTION
**Pull request by IreNox**
Hi, I got errors from duofern after update HA to 2021.06 or so. After some investigation I found out the HA code looks like `schedule_update_ha_state` function is deprecated so I change it to `async_schedule_update_ha_state`. That fixed the errors and missing updates for me. But I'm not a HA/Python pro so not sure this is correct/best fix. Please have a look.

### CODE REVIEW

**Comment by gluap** [comment]
hi @IreNox, thank you a lot for taking this into your own hands and sorry for taking so (very) long. I tried to reproduce the issue with complaints about ``schedule_update_ha_state`` deprecation but my logs have no messages about deprecation in that regard. I updated homeassistant to 2021-09 expecting to see a message about this with no troubles. Could you tell me where you got the error message and what it was saying exactly?

Actually I was about to merge the pull request but wanted to test first because I wasn't sure whether it was permissible to call an asynchronous method from the callback. I do believe that homeassistant is pushing for components to become more asynchronous, so I was expecting a deprecation note like you said for a long time. Still I'd like to be able to reproduce the issue before merging the fix.

Cheers and thank you agian for taking initiative!

**Comment by IreNox** [comment]
Sorry my last fix was totally wrong. It hides the problem but didn't solve it. The actual problem is that the device is added to the device list before it gets initialized by `add_devices`. What leads race condition where a exception in the `update_callback` gets fired because the `hass` value isn't set yet in the device.

**Comment by IreNox** [comment]
Sorry my last fix was totally wrong. The problem was that I had disabled one cover and the update call throws an exception in this case. I added an if. Also listen to the HA started event and start `stick` in the callback to save 5 seconds start up time.

**Review by gluap — APPROVED** [review]

**Comment by gluap** [comment]
@IreNox This looks sensible so I merged it right away. Thank you for picking it up again!

**Pull request merged**
