### PR TITLE
Add shutter toggling, shutter manual mode and Devices

### PR DESCRIPTION
**Pull request by t-animal**
I didn't do much around the non-shutter devices, because I don't own one of them, so I couldn't test it.

There's still an issue with the manual mode: It gets transferred to my rollotrons, but after a couple of seconds, the state in home assistant jumps back to the old state. Then, again a couple of seconds later, the state jumps to the new state. I suspect this has something to do with how the duofernstick is updated/updates itself. For my use-case this is good enough, though.

For more info, please refer to the commit-messages.

However, I'm not entirely sure how the sync-service is supposed to be used (I set this up ages ago), but I think it might no longer work with this approach?

### CODE REVIEW

**Comment by gluap** [comment]
Thank you a lot for contributing this - I will test locally and push a beta release if it works.

**Comment by gluap** [comment]
@t-animal The integration works for me.

My guess is the jumping state of the manual mode happens like this:
- Homeassistant sends the command to change it. It "previews" the new state by updating it
- pyduofern_hacs sends the command
- homeassistant asks pyduofern for the current state (it polls every 30 seconds)
- pyduofern reads the current state from duofern_stick python object. duofern_stick has not yet received a status update from the shutter and contains the old state
- once the shutter sends a status update and pyduofern receives it, homeassistant updates to the current state received (which corresponds to the one initially sent)

**Comment by gluap** [comment]
Regarding sync_devices I think having a pairing UI makes it mostly obsolete.

**Comment by gluap** [comment]
To get this running I had to re-add the duofern integration and enter my pairing code. But it automatically had my devices with their desired names once paired.

**Comment by gluap** [comment]
@t-animal do these release nodtes sound sensible to you? 

> **Warning**
> This upgrade may require you to re-enable your duofern integration in HACS as it changes the way duofern is configured (more visual configuration options now).

## What's Changed
### Add shutter toggling, shutter manual mode and Devices by @t-animal in https://github.com/gluap/pyduofern-hacs/pull/28
**Devices**
Shutters are now created as devices containing several entities - The cover device, a toggle switch for shutter toggling and a switch to enable/disable duofern manual mode on shutter devices. 

**Shutter toggling**
Enables access to the toggle feature of duofern. This allows to press the button to reverse to the previous direction.

**Manual mode**
Remote control the *manual mode* some duofern devices expose - will disable the device-side automation of the device.


## New Contributors
* @t-animal made their first contribution in https://github.com/gluap/pyduofern-hacs/pull/28

**Full Changelog**: https://github.com/gluap/pyduofern-hacs/compare/v0.4.3...v0.5.0

**Comment by t-animal** [comment]
Sounds good!

**Comment by t-animal** [comment]
> [Edit: Noticed there is no pairing UI after trying it. My bad. Likely people will have to restart homeassistant then instead]

I guess there must be some way for the integration to notify home assistant of new devices, because other integrations do this. Ideally this would be done by pyduofern-hacs, too. I didn't look into this, because I didn't want to stress my girlfriends patience by meddling with our roller setup :D

**Pull request merged**
